# Generated by Django 4.2.27 on 2026-01-03 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('mood', models.TextField()),
                ('vibe', models.TextField()),
                ('occasion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes'), ('hair', 'Hair'), ('makeup', 'Makeup'), ('accessories', 'Accessories')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='looks/')),
                ('notes', models.TextField(blank=True)),
                ('where_to_buy', models.CharField(blank=True, max_length=200)),
                ('product_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='app.outfitplan')),
            ],
        ),
    ]
