# Generated by Django 4.2.25 on 2026-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitplan',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
