# Generated by Django 4.2.25 on 2026-01-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_outfitplan_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
